### ISSUE TITLE
Support readonly secrets 

### ISSUE THREAD

**Issue by benjaminapetersen** [benjaminapetersen/angular-key-value-editor#30]
This is a "key value pair"... but the value is something complicated that really can't be displayed.  Therefore we probably need a `displayName` property on the entry.

**Comment by benjaminapetersen** [comment]
@rhamilto has something going

**Comment by rhamilto** [comment]
See https://github.com/benjaminapetersen/angular-key-value-editor/pull/33

**Comment by benjaminapetersen** [comment]
Closing this out, think we got something that works.
